export const alert = state => state.alert
export const alertSelect = state => state.alertSelect
export const index = state => state.index
export const country = state => state.country
export const userHead = state => state.userHead
export const userName = state => state.userName
export const tel = state => state.tel
export const mobileSelectStatus = state => state.mobileSelectStatus
export const activeYear = state => state.activeYear
export const activeMonth = state => state.activeMonth
export const birthYear = state => state.birthYear
export const birthMonth = state => state.birthMonth
export const birthDay = state => state.birthDay
export const endYear = state => state.endYear
export const endMonth = state => state.endMonth
export const CVCount = state => state.CVCount
export const loading = state => state.loading
export const interested = state => state.interested
export const tishi = state => state.tishi
